W6D4/ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

W6D4/ninety_nine_cats/app/models/cat.rb
require 'action_view'

class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper
    
    validates :birth_date, :color, :name, :sex, :description, presence: true 

    def age
        time_ago_in_words(birth_date)
    end
end

W6D4/ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    
    def index
        @cats = Cat.all

        render :index
    end

    def show
        @cat = Cat.find(params[:id])

        render :show
    end

end

W6D4/ninety_nine_cats/app/views/cats/index.html.erb
<h1>This shows all the cats</h1>

<% @cats.each do |cat|  %>

<ul>
    <li>Name: <a href=<%= cat_url(cat.id) %>><%= cat.name%></a></li>
    <br>
    <li>Birth Date: <%= cat.birth_date %></li>
    <br>
    <li>Color: <%= cat.color %></li>
    <br>
    <li>Sex: <%= cat.sex %></li>
</ul>

<br>

<p>
    Description: <%= cat.description %>
</p>

<br>


<% end %>

W6D4/ninety_nine_cats/app/views/cats/show.html.erb
<h1>This shows a single cat</h1>



<h1><%= @cat.name %></h1>

<table>
  <tr>
    <th>Attribute</th>
    <th>Value</th>
  </tr>
  <% [:age, :birth_date, :color, :sex].each do |attr_name| %>
    <tr>
      <td><%= attr_name %></td>
      <td><%= @cat.send(attr_name) %></td>
    </tr>
  <% end %>
</table>

W6D4/ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>